### ISSUE TITLE
Неопределённое поведение в workshop3.1

### ISSUE THREAD

**Issue by sergey-shambir** [DavidArutiunian/cppcourse#4]
При запуске программа падает.
Как минимум, время жизни объекта sf::Font намного меньше времени жизни sf::Text, хотя в [документации setText](https://www.sfml-dev.org/documentation/2.4.2/classsf_1_1Text.php#a2927805d1ae92d57f15034ea34756b81) сказано:
>The font argument refers to a font that must exist as long as the text uses it. Indeed, the text doesn't store its own copy of the font, but rather keeps a pointer to the one that you passed to this function. If the font is destroyed and the text tries to use it, the behavior is undefined.

**Comment by DavidArutiunian** [comment]
@sergey-shambir исправлено
